package br.com.ufrn.imd.lpii.classes.main;

public enum Estado {
<<<<<<< HEAD
    STANDBY, CADASTRAR_LOCALIZACAO, CADASTRAR_CATEGORIA_DO_BEM, CADASTRAR_BEM, LISTAR_LOCALIZACOES, LISTAR_CATEGORIAS, LISTAR_BENS_DE_UMA_LOCALIZACAO,
    BUSCAR_BEM_POR_CODIGO, BUSCAR_BEM_POR_NOME, BUSCAR_BEM_POR_DESCRICAO, MOVIMENTAR_BEM, GERAR_RELATORIO, GERAR_RELATORIO_ARQUIVO,
    CARREGAR_DADOS, APAGAR_LOCALIZACAO, APAGAR_CATEGORIA, APAGAR_BEM;
=======
    standby, cadastrar_localizacao, cadastrar_categoria_do_bem, cadastrar_bem, feio, choro;
>>>>>>> 111e96b8d69f7c860586e1c112eda938953a2426
}
