@startuml

title __MAIN's Class Diagram__\n

  namespace br.com.ufrn.imd.lpii.classes.main {
    class br.com.ufrn.imd.lpii.classes.main.Bot {
        {static} ~ bem : String
        {static} ~ botName : String
        {static} ~ categoria : String
        {static} ~ codigo : Integer
        {static} ~ descricao : String
        {static} ~ estado : Estado
        {static} ~ localizacao : String
        {static} ~ nome : String
        {static} ~ status : String
        {static} ~ tombo : String
        {static} + buscarCategoria()
        {static} + buscarCategoria()
        {static} + buscarLocalizacao()
        {static} + buscarLocalizacao()
        {static} + desativarBot()
        {static} + inicializacaoBot()
        {static} - addLine()
        {static} - buscarBem()
        {static} - buscarBem()
        {static} - buscarBemPorDescricao()
        {static} - updateStatus()
    }
  }
  

  namespace br.com.ufrn.imd.lpii.classes.main {
    enum Estado {
      APAGAR_BEM
      APAGAR_CATEGORIA
      APAGAR_LOCALIZACAO
      BUSCAR_BEM_POR_CODIGO
      BUSCAR_BEM_POR_DESCRICAO
      BUSCAR_BEM_POR_NOME
      CADASTRAR_BEM
      CADASTRAR_CATEGORIA_DO_BEM
      CADASTRAR_LOCALIZACAO
      CARREGAR_DADOS
      GERAR_RELATORIO
      GERAR_RELATORIO_ARQUIVO
      LISTAR_BENS_DE_UMA_LOCALIZACAO
      LISTAR_CATEGORIAS
      LISTAR_LOCALIZACOES
      MOVIMENTAR_BEM
      STANDBY
    }
  }
  

  namespace br.com.ufrn.imd.lpii.classes.main {
    class br.com.ufrn.imd.lpii.classes.main.Main {
        {static} + criarTabelas()
        {static} + main()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
